### PR TITLE
Added core fields to mapping

### PR DESCRIPTION
**Pull request by wujku**
Related to this issue: #67

### CODE REVIEW

**Comment by fashxp** [comment]
thx, will check asap

**Comment by fashxp** [comment]
looks great ... do we need a reindex after this is merged?

**Comment by wujku** [comment]
@fashxp Yes, reindex is required after this feature was merged.

**Comment by fashxp** [comment]
a mapping update too I guess?

**Comment by wujku** [comment]
@fashxp mapping update should be fired before reindexing.

**Comment by wujku** [comment]
@fashxp can you create a develop branch with version 3.0 and merge my last two features? I would like to use them in my project.

**Comment by fashxp** [comment]
lets go for v3 as a whole... 

thx very much

**Pull request merged**
