### PR TITLE
Fix messenger configuration

### LINKED ISSUE #239: [Bug]: Invalid option(s) "queue_name" passed to Messenger transport
### Expected behavior

Alternative messenger transport (redis, amqp, etc.) should be supported.

### Actual behavior

Alternative messengers are not supported as the configuration cannot be correctly changed.

### Steps to reproduce

Switch the default transport (doctrine) to alternative transport

```
framework:
    messenger:
        transports:
            pimcore_index_queues:
                dsn: '%env(AMQP_DSN)%/%2f/pimcore_index_queues'
```

Result: 

`[Symfony\Component\Messenger\Exception\LogicException] Invalid option(s) "queue_name" passed to the AMQP Messenger transport.`

The option `queue_name` is still present in the default config, although it is no longer supported by different transports.

https://github.com/pimcore/advanced-object-search/blob/9a4a7e94a3881ae64cdd120fe7629b49b2755249/src/Resources/config/pimcore/config.yml#L1-L7

Issue widely known in the core and other bundles. We are asking ourself, why it is not fixed here yet?

See:
https://github.com/pimcore/data-importer/issues/226
https://github.com/pimcore/pimcore/issues/11355
https://github.com/pimcore/portal-engine/pull/168

### PR DESCRIPTION
**Pull request by studio1gmbh-pimcore**
Changes in this pull request

Resolves  https://github.com/pimcore/advanced-object-search/issues/239

### CODE REVIEW

**Comment by blankse** [comment]
Seems to be a bug. So the target branch should be `5.0`.

**Comment by dvesh3** [comment]
@studio1gmbh-pimcore we need to rebase here as well. There are some unrelated commits.

**Comment by studio1gmbh-pimcore** [comment]
@dvesh3 done

**Review by dvesh3 — APPROVED** [review]

**Comment by dvesh3** [comment]
@studio1gmbh-pimcore thank you!

**Pull request merged**
