### PR TITLE
Added ES8 support

### PR DESCRIPTION
**Pull request by fashxp**
decision needed concerning https://github.com/ongr-io/ElasticsearchDSL which is not yet supporting ES8

### CODE REVIEW

**Comment by jdreesen** [comment]
[ongr-io/ElasticsearchDSL](https://github.com/ongr-io/ElasticsearchDSL) looks pretty abandoned to me. There has been barely any activity in the last few years.

**Comment by fashxp** [comment]
same impression here

**Comment by fashxp** [comment]
concerning elasticsearchDSL: for now we can switch to handcraftedinthealps/elasticsearch-dsl which provides elasticsearch 8 support. but I guess we should get rid of it in the long run, see also #179

**Comment by fashxp** [comment]
### TODOs before merging
- [x] Implement and merge https://github.com/pimcore/advanced-object-search/issues/180
- [x] release https://github.com/pimcore/elasticsearch-client
- [x] bump dependency of https://github.com/pimcore/elasticsearch-client to stable version

**Pull request merged**
