### PR TITLE
Add PimcoreSimpleBackendSearchBundle to Installer and BundleCollection

### LINKED ISSUE #202: [Task]: Keep simplebackendsearch compatibility
### Improvement description

advanced-object-search is only usable if PimcoreSimpleBackendSearchBundle is enabled and installed. 
Enable and install the bundle if pimcore XI is used

### PR DESCRIPTION
**Pull request by mattamon**
## Changes in this pull request  
Resolves #202 

## Additional info  
Enabling and installing the PimcoreSimpleBackendSearchBundle  in the Bundle and Installer

### CODE REVIEW

**Comment by martineiber** [comment]
@mattamon What about the case when someone manually uninstalls the PimcoreSimpleBackendSearchBundle, then the AdvancedObjectSearchBundle is no longer accessible. Should we take this into consideration?

**Comment by mattamon** [comment]
Fair point, we would have to test it, what will happen, but I guess in this case the Menu won't show up.
I guess this is a edge case though.

If you install the PimcoreSimpleBackendSearchBundle manually you have to enable it in the bundles.php and install the bundle.
Same goes for the advanced-object-search. It would not really make sense to just uninstall the PimcoreSimpleBackendSearchBundle  if you still want to use the advanced-object-search right?

If you only install the advanced-object-search the PimcoreSimpleBackendSearchBundle will be installed automatically and you do not have to enable it in the bundles.php. If you then uninstall the PimcoreSimpleBackendSearchBundle I guess it is your own responsibility. 

What bothers me a little is, that if you uninstall the advanced-object-search we cannot simply uninstall the PimcoreSimpleBackendSearchBundle, because we cannot be sure if it is in use or not.

But in general I would say the dev is responsible for the bundle management.

@brusch wdyt?

**Comment by martineiber** [comment]
I have tested this edge case by uninstalling only the PimcoreSimpleBackendSearchBundle. The search menu is no longer displayed, which means that the AdvancedObjectSearchBundle can no longer be used.

**Comment by fashxp** [comment]
> Fair point, we would have to test it, what will happen, but I guess in this case the Menu won't show up. I guess this is a edge case though.
> 
> If you install the PimcoreSimpleBackendSearchBundle manually you have to enable it in the bundles.php and install the bundle. Same goes for the advanced-object-search. It would not really make sense to just uninstall the PimcoreSimpleBackendSearchBundle if you still want to use the advanced-object-search right?
> 
> If you only install the advanced-object-search the PimcoreSimpleBackendSearchBundle will be installed automatically and you do not have to enable it in the bundles.php. If you then uninstall the PimcoreSimpleBackendSearchBundle I guess it is your own responsibility.
> 
> What bothers me a little is, that if you uninstall the advanced-object-search we cannot simply uninstall the PimcoreSimpleBackendSearchBundle, because we cannot be sure if it is in use or not.
> 
> But in general I would say the dev is responsible for the bundle management.
> 
> @brusch wdyt?

yes, it is responsibilitiy of bundle management. Do not uninstall bundles automatically...

**Review by martineiber — APPROVED** [review]
Works fine!

**Pull request merged**
