### PR TITLE
[Bug]: exclude_classes not working correctly

### PR DESCRIPTION
**Pull request by kevinloeber-twocream**
Expected behavior: Pimcore should not try to request the index of exlcuded classes

Actual behavor: If you try to delete an object of an excluded class, an error occured that the index for this class does not exists

Steps to reproduce: Exclude a class and try to delete the object

### CODE REVIEW

**Comment by skoch-twocream** [comment]
Thanks!

**Comment by mattamon** [comment]
Hey @kevinloeber-twocream thank you for your contribution!

I would consider this a bug no? Should we rebase it to 6.0?

**Comment by kevinloeber-twocream** [comment]
Hello @mattamon,

Yes, this is a bug. You can rebase to 6.0 so that continue working with it immediately without errors.

**Comment by mattamon** [comment]
> Hello @mattamon,
> 
> Yes, this is a bug. You can rebase to 6.0 so that continue working with it immediately without errors.

I tried to rebase it now, but unfortunately it is not that easy. Since 6.x has already some commits in it, if I rebase, those commits would also be in 6.0. 
So automatic rebasing does not work in this case. 
Can you please do a proper rebase. You also can open up a new PR where you start with 6.0 to branch off.

**Comment by kevinloeber-twocream** [comment]
Okay, I'll close the PR and open a new one

**Pull request closed without merging**
